# Hey Emacs, this is -*- coding: utf-8; mode: bazel -*-

workspace(
  name = "rh_ts_library",
  managed_directories = {"@npm": ["node_modules"]},
)

git_repository(
  name = "build_bazel_rules_nodejs",
  remote = "https://github.com/ramblehead/bazel-rules-nodejs.git",
  branch = "build_bazel_rules_nodejs-1.0.0-rh_overrides",
)

load("@build_bazel_rules_nodejs//:index.bzl", "yarn_install")

yarn_install(
  name = "npm",
  package_json = "//:package.json",
  yarn_lock = "//:yarn.lock",
)

load("@npm//:install_bazel_dependencies.bzl", "install_bazel_dependencies")

install_bazel_dependencies()

load("@npm_bazel_typescript//:index.bzl", "ts_setup_workspace")

ts_setup_workspace()
